apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zucv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zucv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zucv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zucv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zucv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lfyx-tenant/rhtap-demo-app/hacbs-test-project-zucv@sha256:35f1104946eed22d483bb1d685ebf372040f8a611cbb09dd1128129561eda73d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
